#' Generate input for butterfly plot
#'
#' @param area.input a dataframe with area for all taxonomy level generated by 'calculateArea'
#' @param subtype a string object specifying what cancer subtype to be included
#' @param num_micro an integer indicating how many microbes shoul be included for zoomed up version
#'
#' @return a list with two ggplot2 objects. One for all taxonomy level and another for selected number speficied in 'num_micro'
#' @export
#'
butterfly_input <- function(area.input, subtype, num_micro) {

  data_T <- area.input %>%
    dplyr::filter(grepl("T", type),
           grepl(subtype, type))%>%
    dplyr::select(-type)
  data_O <- area.input %>%
    dplyr::filter(grepl("O", type),
           grepl(subtype, type))%>%
    dplyr::mutate(area = -1*area)%>%
    dplyr::select(-type)

  common.tax <- intersect(data_T$species,data_O$species)

  common.area.all <- data_T %>%
    dplyr::filter(species %in% common.tax)%>%
    dplyr::rename("T.area" = "area")%>%
    dplyr::inner_join(data_O, by = "species")%>%
    dplyr::rename("Taxa" = "species", "O.area" = "area")%>%
    dplyr::mutate(sum.area = T.area + abs(O.area))%>%
    dplyr::arrange(sum.area)%>%
    dplyr::mutate(Taxa=factor(Taxa, levels=Taxa))%>%
    tidyr::gather("type","area",-c("Taxa","sum.area"))


  common.area.head <- data_T %>%
    dplyr::rename("T.area" = "area")%>%
    dplyr::filter(species %in% common.tax)%>%
    dplyr::inner_join(data_O, by = "species")%>%
    dplyr::rename("Taxa" = "species", "O.area" = "area")%>%
    dplyr::mutate(O.area = O.area*-1,
           sum.area = T.area + abs(O.area))%>%
    dplyr::arrange(sum.area)%>%
    tail(n = num_micro)%>%
    dplyr::mutate(Taxa=factor(Taxa, levels=Taxa))%>%
    tidyr::gather("type","area",-c("Taxa","sum.area"))


  common.taxarea.head <- ggplot(common.area.head, aes(x = area, y = Taxa ,fill = type))+
    geom_col(position = "dodge")+
    # theme(axis.text.y=element_blank(),
    #       axis.ticks.y=element_blank())+
    ylab("Taxonomy")+
    xlab("area")

  common.taxarea.all <- ggplot(common.area.all, aes(x = area, y = Taxa ,fill = type))+
    geom_col(position = "stack")+
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank())+
    ylab("Taxonomy")+
    xlab("area")

  x <- list(common.taxarea.all,common.taxarea.head)
  names(x) <- c("common.taxarea.all","common.taxarea.head")
  return(x)
}
