#' Generate input for butterfly plot
#'
#' @param area.input a dataframe with area for all taxonomy level generated by 'calculateArea'
#' @param subtype a string object specifying what cancer subtype to be included
#' @param num_micro an integer indicating how many microbes shoul be included for zoomed up version
#'
#' @return a list with two ggplot2 objects. One for all taxonomy level and another for selected number speficied in 'num_micro'
#' @importFrom dplyr mutate group_by summarise filter left_join
#' @importFrom ggplot2 ggplot aes geom_col geom_text geom_vline geom_histogram
#' @importFrom ggplot2 geom_density facet_wrap theme element_text element_blank
#' @importFrom ggplot2 theme_classic scale_x_continuous scale_y_continuous ggtitle xlab ylab
#' @importFrom stats pnorm quantile sd ave
#' @importFrom utils tail
#' @examples
#' # Create mock area input data
#' area.input <- data.frame(
#'   type    = c("T_DDLPS", "T_DDLPS", "T_DDLPS",
#'               "T_LMS",   "T_LMS",
#'               "O_DDLPS", "O_DDLPS", "O_DDLPS",
#'               "O_LMS",   "O_LMS"),
#'   species = c("Proteobacteria", "Firmicutes", "Bacteroidetes",
#'               "Proteobacteria", "Firmicutes",
#'               "Proteobacteria", "Firmicutes", "Bacteroidetes",
#'               "Proteobacteria", "Firmicutes"),
#'   area    = c(0.45, 0.30, 0.25,
#'               0.60, 0.40,
#'               0.35, 0.40, 0.25,
#'               0.50, 0.50)
#' )
#'
#' # Run for DDLPS subtype, showing top 3 microbes
#' result <- butterfly_input(area.input, subtype = "DDLPS", num_micro = 3)
#'
#' # Result is a list with two ggplot objects
#' # result$common.taxarea.all   - stacked bar chart of all shared taxa
#' # result$common.taxarea.head  - dodged bar chart of top num_micro taxa
#' @export
#'
butterfly_input <- function(area.input, subtype, num_micro) {

  data_T <- area.input %>%
    dplyr::filter(grepl("T", type),
           grepl(subtype, type))%>%
    dplyr::select(-type)
  data_O <- area.input %>%
    dplyr::filter(grepl("O", type),
           grepl(subtype, type))%>%
    dplyr::mutate(area = -1*area)%>%
    dplyr::select(-type)

  common.tax <- intersect(data_T$species,data_O$species)

  common.area.all <- data_T %>%
    dplyr::filter(species %in% common.tax)%>%
    dplyr::rename("T.area" = "area")%>%
    dplyr::inner_join(data_O, by = "species")%>%
    dplyr::rename("Taxa" = "species", "O.area" = "area")%>%
    dplyr::mutate(sum.area = T.area + abs(O.area))%>%
    dplyr::arrange(sum.area)%>%
    dplyr::mutate(Taxa=factor(Taxa, levels=Taxa))%>%
    tidyr::gather("type","area",-c("Taxa","sum.area"))


  common.area.head <- data_T %>%
    dplyr::rename("T.area" = "area")%>%
    dplyr::filter(species %in% common.tax)%>%
    dplyr::inner_join(data_O, by = "species")%>%
    dplyr::rename("Taxa" = "species", "O.area" = "area")%>%
    dplyr::mutate(O.area = O.area*-1,
           sum.area = T.area + abs(O.area))%>%
    dplyr::arrange(sum.area)%>%
    tail(n = num_micro)%>%
    dplyr::mutate(Taxa=factor(Taxa, levels=Taxa))%>%
    tidyr::gather("type","area",-c("Taxa","sum.area"))


  common.taxarea.head <- ggplot(common.area.head, aes(x = area, y = Taxa ,fill = type))+
    geom_col(position = "dodge")+
    # theme(axis.text.y=element_blank(),
    #       axis.ticks.y=element_blank())+
    ylab("Taxonomy")+
    xlab("area")

  common.taxarea.all <- ggplot(common.area.all, aes(x = area, y = Taxa ,fill = type))+
    geom_col(position = "stack")+
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank())+
    ylab("Taxonomy")+
    xlab("area")

  x <- list(common.taxarea.all,common.taxarea.head)
  names(x) <- c("common.taxarea.all","common.taxarea.head")
  return(x)
}
