#' plot empirical test object and output statistics
#'
#' @param list a list object generated by function "emp"
#' @param plot.title a character object specifying the plot title
#' @return a ggplot2 object and a dataframe
#' @examples
#' \donttest{
#' ## Create a small reproducible example dataset
#' set.seed(123)
#'
#' ## Each list element represents a Taxa with bootstrap seeds
#' ex1 <- data.frame(
#'   Taxa  = "k__Bacteria;p__Firmicutes",
#'   seeds = c("original", as.character(2:20)),
#'   area  = c(0.08, rlnorm(19, meanlog = -2.5, sdlog = 0.6))
#' )
#'
#' ex2 <- data.frame(
#'   Taxa  = "k__Bacteria;p__Proteobacteria",
#'   seeds = c("original", as.character(2:20)),
#'   area  = c(0.15, rlnorm(19, meanlog = -2.0, sdlog = 0.5))
#' )
#'
#' input_list <- list(ex1, ex2)
#'
#' ## Run function
#' out <- plot_emp(
#'   list = input_list,
#'   plot.title = "Empirical Area Distributions"
#' )
#'
#' ## Inspect returned objects
#' out$z        # ggplot object
#' out$stat.out # summary statistics
#' }
#' @noRd
#'

plot_emp <- function(list, plot.title){
  level_order <- c("original",as.character(seq(2,length(list[[1]]$seeds),1)))
  b <- do.call(rbind,list)%>%
    mutate(seeds = factor(seeds, levels=level_order),
           area = as.numeric(as.character(area)),
           Taxa = gsub("[a-z]__(.*)","\\1",.$Taxa))

  stat.out <- b %>%
    group_by(Taxa)%>%
    summarise(sd = sd(area[-1]), ave = mean(area[-1]), o.area = area[1])%>%
    mutate(pval = paste("p-value=",
                        format(round((1-pnorm(log(o.area), mean = log(ave), sd = log(sd)))/100, 4), nsmall = 4),
                        sep=""))

  plot.in <- b %>%
    filter(!seeds == "original")



  z <- ggplot(plot.in, aes(x = log(area)))+
    geom_histogram(aes(y = after_stat(density)),binwidth = 0.1)+
    geom_density(alpha = 0.5)+
    facet_wrap(~Taxa,scales='free')+
    geom_vline(data = stat.out, aes(xintercept = log(o.area)),color="red")+
    geom_text(x = -5, y = 0.3, aes(label = pval), data = stat.out, size = 4)+
    theme_classic()+
    theme(strip.text.x = element_text(size = 10))+
    scale_x_continuous(limits=c(-10,8)) +
    scale_y_continuous(limits=c(0,0.3))+
    ggtitle(plot.title)

  x <- list(z,stat.out)
  names(x) <- c("z","stat.out")
  return(x)
}
